# File              : docker-compose.decentralised.yaml
# Author            : Sheetal Reddy <sheetal.reddy@ai.se>
# Date              : 22.12.2020
# Last Modified Date: 22.12.2020
# Last Modified By  : Sheetal Reddy <sheetal.reddy@ai.se>


version: '3.3'
services:
  client1:
    environment:
      - GET_HOSTS_FROM=dns
    image: "scaleoutsystems/nlp-client:latest"
    build:
      context: .
    working_dir: /app
    command: /bin/bash -c "fedn run client -in fedn-network.yaml"
    volumes:
      - ./data/data1:/app/data

  client2:
    environment:
      - GET_HOSTS_FROM=dns
    image: "scaleoutsystems/nlp-client:latest"
    build:
      context: .
    working_dir: /app
    command: /bin/bash -c "fedn run client -in fedn-network.yaml"
    volumes:
      - ./data/data2:/app/data


networks:
  default:
    external:
      name: fedn_default
